#!/bin/bash


 cp -r ~/Public/xfce\ panel\ /ice/xfce4/ ~/.config/ &
xrdb merge ~/Public/xresources/base/.Xresources  && xrdb ~/Public/xresources/base/.Xresources &
 cp -r ~/Public/theme\ and\ icons/dwm/.gtkrc-2.0 ~/
cp -r ~/Public/theme\ and\ icons/dwm/settings.ini  ~/.config/gtk-3.0/
xfce4-panel & 
feh --bg-fill ~/Pictures/wall/gnu.jpg &

cp -r ~/Public/rofi/dwm/rofi/ ~/.config/

