#! /bin/sh

sxhkd &

killal -q bar &
cp -r ~/Public/poly/bsp/polybar/ ~/.config/ &
~/.config/polybar/launch.sh &


#wall 
feh --bg-fill ~/Pictures/wall/rms.jpg &

# rofi /gtk and icons 
cp -r ~/Public/rofi/bspwm\ /rofi/ ~/.config/ &
cp -r ~/Public/theme\ and\ icons/flux/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/flux/settings.ini  ~/.config/gtk-3.0/ &

 


#for terminal  
xrdb merge ~/Public/xresources/dracula/.Xresources

bspc monitor -d I II III IV V VI VII


bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 27


bspc config normal_border_color "#c3aed6"
bspc config active_border_color "#fbcffc"
bspc config focused_border_color "#c3aed6"

